name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtiomTr/jest-coverage-report-action@v2
    permissions:
      contents: read
      pull-requests: write
